core/urls.py
from django.urls import path, include
#from core.views import index
from core import views

app_name = 'core'

urlpatterns = [
    #index page
    path('', views.index, name = "index"),

    #shop page
    path('products/', views.product_list, name = 'product'),

    #product-detail page
    path('product/<pid>/', views.product_detail_view, name = 'product-detail'),

    #category
    path('category/', views.category_list_view, name = 'category'),

    #category product list 
    path('category/<cid>/', views.category_product_list_view, name = 'category-product-list'),

    #tag product list
    path('products/tag/<slug:tag_slug>/', views.tag_list, name="tags"),
    
    #review
    path('ajax-add-review/<int:pid>/', views.ajax_add_review, name='ajax_add_review'),

    #search
    path('search/', views.search_view, name='search'),

    #filter-product
    #path('filter-product/', views.filter_product, name="filter-product"),

    #cart
    path('add-to-cart/', views.add_to_cart, name = 'add-to-cart'),
    path('cart/', views.cart_view, name='cart'),
    path('delete-from-cart/', views.delete_item_from_cart, name='delete-from-cart'),
    path('update-cart', views.update_cart, name='update-cart'),

    #checkout
    path('checkout/', views.checkout_view, name='checkout'),

    #paypal payment
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-completed/', views.payment_completed_view, name='payment-completed'),
    path('payment-failed/', views.payment_failed_view, name='payment-failed'),
    
    #user profile
    path('dashboard/', views.customer_dashboard, name='dashboard'),
    path('delete_contact/', views.delete_contact, name='delete-contact'),
    path('delete_address/', views.delete_address, name='delete-address'),

    #Brand
    path('brand/<bid>/', views.brand_product_list_view, name = 'brand-product-list'),

    #wishlist
    path('wishlist/', views.wishlist_view, name = 'wishlist'),
    path('add-to-wishlist/', views.add_to_wishlist, name='add-to-wishlist'),
    path('remove-from-wishlist/', views.remove_wishlist, name='remove-from-wishlist'),

    #contact us
    path('contact/', views.Contact_us_view, name='contact'),

    #order
    path('orders/', views.orders_view, name='Orders'),

    #invoice pdf download
    path('invoice/', views.Invoice, name='Invoice'),
    
    #get total cart amount every second
    #path('get_cart_total/', views.get_cart_total, name='get_cart_total')

    #determine the address selectd by the user on the invoice page
    path('update_selected_address/', views.update_selected_address, name='selected_address'),

    #stripe payment
    #path('create_checkout_session/', views.create_checkout_session, name='create-checkout-session'), 

    #privacy policy page
    path('privacy-policy/', views.privacy, name='privacy-policy'),


    #order invoice from order page
    path('order_invoice/<int:order_id>/' , views.order_invoice, name='Order_invoice'),

    #Terms-conditions page
    path('terms-conditions/', views.Terms_Conditions, name='terms-conditions'),

 
    



   
    






]

vishw/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path('User/', include("userauths.urls")), 

    path('ckeditor/', include("ckeditor_uploader.urls")), 

    path('reset_password', auth_views.PasswordResetView.as_view(template_name="reset_password.html"), name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_send.html"), name="password_reset_done"),

    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name="password_reset_complete"),
]

if settings.DEBUG:
     urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/forms.py
from django import forms
from core.models import ProductReview
from userauths.models import Profile

class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = ['user', 'product', 'review', 'rating']

    widgets = {
        'user': forms.HiddenInput(),
        'product': forms.HiddenInput(),
        'review': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write your review here'}),
        'rating': forms.TextInput(attrs={'type': 'hidden'}),
    }





class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'image', 'phone', 'secondary_phone', 'email'] 

class ContactForm(forms.Form):
    title = forms.ChoiceField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')])
    number = forms.CharField(max_length=20)

class AddressForm(forms.Form):
    title = forms.ChoiceField(choices=[('home', 'Home'), ('office', 'Office'), ('business', 'Business')], label='Title')
    address = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter your address'}))

core/views.py
from django.shortcuts import render, get_object_or_404
from core.models import Products, Category, ProductImages, ProductReview, Wishlist, Brand, Contact_Us, Order, OrderItem, TermAndConditions
from taggit.models import Tag
from django.db.models import Count, Avg, Q
from core.forms import ProductReviewForm
from django.http import HttpResponse, JsonResponse
from django.views.decorators.http import require_POST
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.template.loader import render_to_string
from django.shortcuts import redirect
from django.contrib import messages
from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm
from django.contrib.auth.decorators import login_required
from userauths.models import Profile
from django.db.models import Avg
from .models import ProductReview
from dal import autocomplete
from django.core import serializers
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from userauths.models import Profile, Address
from .forms import ProfileForm, ContactForm, AddressForm   
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.html import strip_tags
from django.db.models import F, FloatField, Value
from django.db.models.functions import Replace, Cast, Round
import pdfkit
import os
import locale
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from io import BytesIO
from django.contrib import messages
from django.shortcuts import render
from .models import Order, OrderItem
from datetime import timedelta
import locale
from django.http import HttpResponse
from django.template.loader import render_to_string
from weasyprint import HTML
from django.db.models import Avg, Count
from django.shortcuts import render
from .models import Products, Category, Brand, ProductReview


def index(request):
    # Fetch products and related data
    products = Products.objects.all().order_by('-id')[:15]
    categories = Category.objects.annotate(product_count=Count('category'))
    featured_products = Products.objects.filter(featured=True)
    brands = Brand.objects.annotate(product_count=Count('brand'))
    mobile_phones = Products.objects.filter(mobile_phone=True)[:8]

    # Calculate average ratings
    product_sets = [products, featured_products, mobile_phones]
    for product_set in product_sets:
        for product in product_set:
            product.average_rating = ProductReview.objects.filter(product=product).aggregate(Avg('rating'))['rating__avg']

    context = {
        "products": products,
        "categories": categories,
        "featured_products": featured_products,
        "brands": brands,
        "mobile_phones": mobile_phones
    }
    
    return render(request, 'Core/index.html', context)




def product_list(request):
    # Fetch all products and brands
    all_products = Products.objects.all().order_by('-id')
    brands = Brand.objects.all()

    # Get filter parameters from request
    selected_category_ids = request.GET.getlist('category')
    selected_brand_ids = request.GET.getlist('brand')
    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')
    selected_rating = request.GET.get('rating')

    # Apply filters
    if selected_category_ids:
        all_products = all_products.filter(category__id__in=selected_category_ids)
    if selected_brand_ids:
        all_products = all_products.filter(brand__id__in=selected_brand_ids)
    if min_price:
        all_products = all_products.filter(price__gte=float(min_price))
    if max_price:
        all_products = all_products.filter(price__lte=float(max_price))
    if selected_rating and selected_rating != 'None':
        all_products = all_products.annotate(
            rounded_rating=Round(Avg('reviews__rating'))
        ).filter(rounded_rating=selected_rating)

    # Calculate average rating for each product
    all_products = all_products.annotate(
        average_rating=Avg('reviews__rating')
    )

    # Paginate filtered products
    paginator = Paginator(all_products, 12)
    page_number = request.GET.get('page')
    try:
        products = paginator.page(page_number)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    # Generate pagination URL with filters
    pagination_url = request.GET.copy()
    if 'page' in pagination_url:
        del pagination_url['page']
    pagination_url = pagination_url.urlencode()

    context = {
        "products": products,
        "selected_category_ids": selected_category_ids,
        "selected_brand_ids": selected_brand_ids,
        "brands": brands,
        "selected_rating": selected_rating,
        "pagination_url": f"/products/?{pagination_url}"
    }

    return render(request, 'Core/shop-3column.html', context)




def category_list_view(request):
    categories = Category.objects.all()

    context = {

        "categories":categories,

    }
    return render(request, 'Core/all-category.html', context )





def category_product_list_view(request, cid):
    category = get_object_or_404(Category, cid=cid)
    all_products = Products.objects.filter(category=category).order_by('-id')
    brands = Brand.objects.all()

    selected_brand_ids = request.GET.getlist('brand')
    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')
    selected_rating = request.GET.get('rating')

    all_products = filter_products(all_products, selected_brand_ids, min_price, max_price, selected_rating)

    # Calculate average rating for each product
    all_products = all_products.annotate(average_rating=Avg('reviews__rating'))

    # Paginate filtered products
    products_per_page = 12
    paginator = Paginator(all_products, products_per_page)
    page_number = request.GET.get('page')
    products = get_paginated_products(paginator, page_number)

    pagination_url = build_pagination_url(cid, selected_brand_ids, min_price, max_price, selected_rating)

    context = {
        "products": products,
        "selected_brand_ids": selected_brand_ids,
        "brands": brands,
        "selected_rating": selected_rating,
        "pagination_url": pagination_url,
        "category": category,
    }

    return render(request, 'Core/category-product-list.html', context)

def filter_products(products, brand_ids, min_price, max_price, rating):
    if brand_ids:
        products = products.filter(brand__id__in=brand_ids)
    
    if min_price or max_price:
        products = products.annotate(
            price_num=Cast(Replace('price', Value(','), Value('')), output_field=FloatField())
        )
        if min_price:
            products = products.filter(price_num__gte=min_price)
        if max_price:
            products = products.filter(price_num__lte=max_price)
    
    if rating and rating != 'None':
        products = products.annotate(rounded_rating=Round(Avg('reviews__rating'))).filter(rounded_rating=rating)
    
    return products

def get_paginated_products(paginator, page_number):
    try:
        return paginator.page(page_number)
    except PageNotAnInteger:
        return paginator.page(1)
    except EmptyPage:
        return paginator.page(paginator.num_pages)

def build_pagination_url(cid, brand_ids, min_price, max_price, rating):
    url = f"/category/{cid}/"
    params = []
    
    if brand_ids:
        params.extend([f"brand={brand_id}" for brand_id in brand_ids])
    if min_price:
        params.append(f"min_price={min_price}")
    if max_price:
        params.append(f"max_price={max_price}")
    if rating:
        params.append(f"rating={rating}")
    
    if params:
        url += "?" + "&".join(params)
    
    return url


from django.core.paginator import Paginator

def brand_product_list_view(request, bid):
    brand = Brand.objects.get(bid=bid)
    products = Products.objects.filter(brand=brand)
    categories = Category.objects.all()
    total_products_count = products.count()

    # Handle category filtering
    selected_category_id = request.GET.get('category')
    if selected_category_id and selected_category_id != 'all':
        products = products.filter(category__id=selected_category_id)
        selected_category_id = int(selected_category_id)  # Convert to integer

    # Calculate average rating for each product
    for product in products:
        product.average_rating = ProductReview.objects.filter(product=product).aggregate(Avg('rating'))['rating__avg']

    # Create a Paginator object
    paginator = Paginator(products, 10)  # Show 15 products per page

    # Get the page number from the GET request
    page_number = request.GET.get('page')

    # Get the products for the current page
    products = paginator.get_page(page_number)

    context = {
        "brand": brand,
        "products": products,
        "categories": categories,
        "selected_category_id": selected_category_id,  # Pass selected category ID to template
        "total_products_count": total_products_count,
                }
    return render(request, 'Core/brand-product-list.html', context)



from django.core.exceptions import ObjectDoesNotExist


def product_detail_view(request, pid):
    try:
        product = Products.objects.get(pid=pid)

        # Check if the user has a delivered order containing the current product
        user_has_delivered_order = False
        if request.user.is_authenticated:
            try:
                OrderItem.objects.get(order__user=request.user, order__order_status=Order.ORDER_DELIVERED, product=product)
                user_has_delivered_order = True
            except OrderItem.DoesNotExist:
                pass

templates/Core/cart.html
{% extends "partials/base.html" %}
{% load static %}
{% block content %}

       
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner"id="cart-list" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>cart</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'core:index' %}>Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Cart</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    WISHLIST PART START
        =======================================-->
        <section class="inner-section wishlist-part">
            {% if cart_data %}

            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="table-scroll">
                            <table class="table-list">
                                <thead>
                                    <tr>
                                        <th scope="col">Serial</th>
                                        <th scope="col">Product</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Price</th>
                                        <th scope="col">status</th>
                                        <th scope="col">Quantity</th>
                                        <th scope="col">total</th>
                                        <th scope="col">action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                    {% for product_id, item in cart_data.items %}
                                    <tr class="remove-cart-item">
                                        <h6> {{ item.id }} </h6>
                                       
                                        <td class="table-serial"><h6>{{ forloop.counter }}</h6></td>
       
                                      

                                        <td class="table-image"><img src="{{ item.image }}" alt="product"></td>
                                        <td class="table-name"><a href={% url "core:product-detail" item.pid %}><h6>{{ item.title|truncatechars:20 }}</h6></a></td>
                                        <td class="table-price"><h6><span></span><span class="update-product-price">₹{{ item.price }}</span></h6></td>
                                        <td class="table-status"><h6 class="stock-out">{% if item.stock == 0 or item.stock == "0" %}
                                            Stock out
                                        {% else %}
                                            In stock
                                        {% endif %}
                                         </h6></td>
                                        <td class="table-price">
                                            <p>
                                                <h6>
                                                    <input type="number" class="styled-number-input w-75 product-quantity-{{ product_id }} quantity-update" data-index="{{ product_id }}" id="product-quantity-cart" max="{{ item.stock }}" min="1" value="{{ item.qty }}" {% if item.stock == 0 or item.stock == "0" %}disabled{% endif %} oninput="checkQuantity(this)">
                                                </h6>
                                            </p>
                                        </td>
                                        
                                        
                                            
                                        <td class="table-price product-total-{{ product_id }}"> <h6>₹{{ item.total_price }}</h6> </td>

                                        <td class="table-action">
                                            <a class="view" href="#" title="Quick View" data-bs-toggle="modal"data-bs-target="#product-view-{{ product_id }}" data-product-id="{{ item.product_id }}"><i class="fas fa-eye"></i></a>
                                            <button class="trash delete-product" data-product="{{ product_id }}" title="Remove Wishlist"><i class="icofont-trash"></i></button>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center mt-5">
                            <!--<button class="btn btn-outline">
                                Load more items
                            </button>-->
                            <a class="cart-checkout-btn" href="{% url 'core:checkout' %}">
                                <span class="checkout-label">Proceed to Checkout</span>
                                <span class="checkout-price" id="cart-total-amount1">₹{{ cart_total_amount }}</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
            <section class="error-part">
                <div class="container">
                    <h1>Your cart is empty!</h1>
                    <img class="img-fluid" src="{% static "images/d438a32e-765a-4d8b-b4a6-520b560971e8.webp" %}" alt="error">
                    <h3>Add items to it now.</h3>
                   
                    <a href="{% url "core:product" %}">Shop now</a>
                </div>
            </section>
            {% endif %}
        </section>
        <!--=====================================
                    WISHLIST PART END
        =======================================-->


        




        {% endblock content %}

templates/Core/payment-completed.html
{% extends "partials/base.html" %}
{% load static %}
{% block content %}
{% load humanize %}
<!--================

        <!--=====================================
                    BANNER PART START
        =======================================-->
   
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    INVOICE PART START
        =======================================-->
        <section class="inner-section invoice-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="alert-info">
                            <p>Hey {{ request.user|title }}, We have recieved your order.</p>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="account-card">
                            <div class="account-title">
                                <h4>order recieved</h4>
                            </div>
                            <div class="account-content">
                                <div class="invoice-recieved">
                                    <h6>order number <span>{{ order_id }}</span></h6>
                                    <h6>order date <span>{{ order_time|date:"jS F Y" }}</span></h6>
                                    <h6>total amount <span>₹{{ cart_total_amount|floatformat:"0"|intcomma }}</span></h6>
                                    {% if payment_method == 'cash_on_delivery' %}
                                    <h6>Payment Method <span>Cash on Delivery</span></h6>
                                {% else %}
                                    <h6>Payment Method <span>PayPal</span></h6>
                                {% endif %}
                                
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="account-card">
                            <div class="account-title">
                                <h4>Order Details</h4>
                            </div>
                            <div class="account-content">
                                <ul class="invoice-details">
                                    <li>
                                        <h6>Total Item</h6>
                                        <p>{{ total_quantity }} Items</p>
                                    </li>
                                    <li>
                                        <h6>Order Time</h6>
                                        <p>{{ order_time|time:"g.iA" }} {{ order_time|date:"d-m-Y" }}
                                        </p>
                                    </li>
                                    <li>
                                        <h6>Delivery</h6>
                                        <p> within {{ delivery_time|date:"d-m-Y" }} 
                                        </p>
                                    </li>
                                    <li>
                                        <h6>Delivery Location</h6>
                                       
                                        <p><b>{{ selected_address.first_name }} {{ selected_address.last_name }}</b> - {{ selected_address.street_address }}, {{ selected_address.city_district_town }}, {{ selected_address.state }}-{{ selected_address.pincode }}</p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="account-card">
                            <div class="account-title">
                                <h4>Amount Details</h4>
                            </div>
                            <div class="account-content">
                                <ul class="invoice-details">
                                    <li>
                                        <h6>Sub Total</h6>
                                        <p>₹{{ sub_total_old_price }}</p>
                                    </li>
                                    <li>
                                        <h6>discount</h6>
                                        <p>₹{{ discount }}</p>
                                    </li>
                                    <li>
                                        <h6>delivery fee </h6>
                                        <p> ₹{{ delivery_fee }}
                                    </li>
                                    {% if payment_method == 'cash_on_delivery' %}
                                    <li>

                                        <h6>Payment Method</h6>
                                        <p>Cash On Delivery</p>
                                    </li>
                                    {% else %}
                                    <li>

                                        <h6>Payment Method</h6>
                                        <p>PayPal</p>
                                    </li>
                                    {% endif %}
                                    <li>
                                        <h6>Total<small>(Incl. VAT)</small></h6>
                                        <p>₹{{ cart_total_amount|floatformat:"0"|intcomma }}</p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="table-scroll">
                            <table class="table-list">
                                <thead>
                                    <tr>
                                        <th scope="col">Serial</th>
                                        <th scope="col">Product</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Price</th>
                                        <th scope="col">quantity</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for product_id, item in cart_data.items %}
                                    <tr>
                                        <td class="table-serial"><h6>{{ forloop.counter }}</h6></td>
                                        <td class="table-image"><img src="{{ item.image }}" alt="product"></td>
                                        <td class="table-name"><a href={% url "core:product-detail" item.pid %}><h6>{{ item.title|truncatechars:55 }}</h6></a></td>
                    
                                        <td class="table-price"><h6><span>₹</span>{{ item.price }}</h6></td>
                                        <td class="table-quantity"><h6>{{ item.qty }}</h6></td>
                                    </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {% if payment_method == 'cash_on_delivery' %}
                <div class="row">
                    <div class="col-lg-12 text-center mt-5">
                        <a class="btn btn-inline" href="{% url "core:Orders" %}">
                            <i class="icofont-download"></i>
                            <span>track order</span>
                        </a>
                        <div class="back-home">
                            <a href="{% url 'core:index' %}">Back to Home</a>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="row">
                    <div class="col-lg-12 text-center mt-5">
                        <a class="btn btn-inline" href="{% url "core:Invoice" %}">
                            <i class="icofont-download"></i>
                            <span>Download Invoice</span>
                        </a>
                        <div class="back-home">
                            <a href="{% url 'core:index' %}">Back to Home</a>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </section>
        <!--=====================================
                    INVOICE PART END
        =======================================-->


       

        {% endblock content %}
    