core/urls.py
from django.urls import path, include
#from core.views import index
from core import views

app_name = 'core'

urlpatterns = [
    #index page
    path('', views.index, name = "index"),

    #shop page
    path('products/', views.product_list, name = 'product'),

    #product-detail page
    path('product/<pid>/', views.product_detail_view, name = 'product-detail'),

    #category
    path('category/', views.category_list_view, name = 'category'),

    #category product list 
    path('category/<cid>/', views.category_product_list_view, name = 'category-product-list'),

    #tag product list
    path('products/tag/<slug:tag_slug>/', views.tag_list, name="tags"),
    
    #review
    path('ajax-add-review/<int:pid>/', views.ajax_add_review, name='ajax_add_review'),

    #search
    path('search/', views.search_view, name='search'),

    #filter-product
    #path('filter-product/', views.filter_product, name="filter-product"),

    #cart
    path('add-to-cart/', views.add_to_cart, name = 'add-to-cart'),
    path('cart/', views.cart_view, name='cart'),
    path('delete-from-cart/', views.delete_item_from_cart, name='delete-from-cart'),
    path('update-cart', views.update_cart, name='update-cart'),

    #checkout
    path('checkout/', views.checkout_view, name='checkout'),

    #paypal payment
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-completed/', views.payment_completed_view, name='payment-completed'),
    path('payment-failed/', views.payment_failed_view, name='payment-failed'),
    
    #user profile
    path('dashboard/', views.customer_dashboard, name='dashboard'),
    path('delete_contact/', views.delete_contact, name='delete-contact'),
    path('delete_address/', views.delete_address, name='delete-address'),

    #Brand
    path('brand/<bid>/', views.brand_product_list_view, name = 'brand-product-list'),

    #wishlist
    path('wishlist/', views.wishlist_view, name = 'wishlist'),
    path('add-to-wishlist/', views.add_to_wishlist, name='add-to-wishlist'),
    path('remove-from-wishlist/', views.remove_wishlist, name='remove-from-wishlist'),

    #contact us
    path('contact/', views.Contact_us_view, name='contact'),

    #order
    path('orders/', views.orders_view, name='Orders'),

    #invoice pdf download
    path('invoice/', views.Invoice, name='Invoice'),
    
    #get total cart amount every second
    #path('get_cart_total/', views.get_cart_total, name='get_cart_total')

    #determine the address selectd by the user on the invoice page
    path('update_selected_address/', views.update_selected_address, name='selected_address'),

    #stripe payment
    #path('create_checkout_session/', views.create_checkout_session, name='create-checkout-session'), 

    #privacy policy page
    path('privacy-policy/', views.privacy, name='privacy-policy'),


    #order invoice from order page
    path('order_invoice/<int:order_id>/' , views.order_invoice, name='Order_invoice'),

    #Terms-conditions page
    path('terms-conditions/', views.Terms_Conditions, name='terms-conditions'),

 
    



   
    






]

userauths/urls.py
from django.urls import path
from userauths import views
from userauths.views import CustomPasswordChangeView


app_name = 'userauths'

urlpatterns = [
    path("sign-up/", views.register_view, name = "sign-up"),
    path("login/", views.login_view, name = "login"),
    path("sign-out/", views.logout_view, name = "sign-out"),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change-password'),
    path('activate/', views.activate_account_view, name="activate"),
   path('activate_account/', views.activate_account, name="activate-account"),
   path('activation-code', views.activate_code, name="activate-code")

]

vishw/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path('User/', include("userauths.urls")), 

    path('ckeditor/', include("ckeditor_uploader.urls")), 

    path('reset_password', auth_views.PasswordResetView.as_view(template_name="reset_password.html"), name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_send.html"), name="password_reset_done"),

    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name="password_reset_complete"),
]

if settings.DEBUG:
     urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    email = models.EmailField(unique=True, null=True)
    username = models.CharField(max_length=100, unique=True)
    activation_code = models.CharField(max_length=6, blank=True, null=True)  # Field to store activation code
    
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username
    

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None, related_name='profile')
    username = models.CharField(max_length=200, null=True, blank=True)
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to="image", default=None, null=True, blank=True)
    phone = models.CharField(max_length=200, null=True, blank=True)
    secondary_phone = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(unique=True, null=True, blank=True)
    

    def __str__(self):
        return self.first_name if self.first_name else str(self.user)



class Address(models.Model):
    TITLE_CHOICES = [
        ('home', 'Home'),
        ('office', 'Office'),
        ('business', 'Business'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='userauths_addresses')
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    title = models.CharField(max_length=10, choices=TITLE_CHOICES, null=True, default='Home')
    street_address = models.TextField()
    city_district_town = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    pincode = models.CharField(max_length=10)

    def __str__(self):
        return f'{self.title} - {self.street_address}, {self.city_district_town}, {self.state}, {self.pincode}'

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.core.validators import RegexValidator



class UserRegisterForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Username", "class": "form-control", "id":"username_input"}),
        max_length=20,  # Ensures username length is not more than 20
        validators=[
            RegexValidator(
                r'^[a-zA-Z0-9._]+$',  # Regex allowing only letters, numbers, dot, and underscore
                'Username can only contain letters, numbers, dots, and underscores',
            ),
            RegexValidator(
                r'^[^\s]*$',  # Regex ensuring no whitespace
                'Username must not contain any whitespace',
            ),
        ],
    )
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email", "class": "form-control"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password", "class": "form-control"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password", "class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'email']







class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Customize form fields or labels if needed
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

userauths/views.py
from django.contrib.auth import login, authenticate, get_user_model
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from userauths.forms import UserRegisterForm, CustomPasswordChangeForm
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

User = get_user_model()

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from .utils import generate_activation_code
from userauths.models import User
from django.db.models import Q

def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            
            # Check if username or email already exists
            if User.objects.filter(username=username).exists():
                messages.warning(request, "Username already exists. Please choose a different one.")
                return redirect('userauths:register')
            elif User.objects.filter(email=email).exists():
                messages.warning(request, "Email already exists. Please choose a different one.")
                return redirect('userauths:register')
            
            user = form.save(commit=False)
            user.is_active = False  # Set the user as inactive until activation
            user.activation_code = generate_activation_code()  # Generate activation code
            user.save()
            
            # Send activation email
            subject = 'Activate Your Account'
            message = f'Hi {user.username},\n\nThank you for registering. Your activation code is: {user.activation_code}\n\nBest regards,\nTeam Vishw'
            from_email = 'khatik.rk111@gmail.com'  # Replace with your email
            to_email = user.email
            send_mail(subject, message, from_email, [to_email])

            messages.success(request, "Your account has been created. Please check your email for the activation code.")
            return redirect("userauths:activate")
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    messages.warning(request, f"{error}")
    else:
        form = UserRegisterForm()
    
    context = {'form': form}
    return render(request, "userauths/sign-up.html", context)


def login_view(request):
    if request.method == "POST":
        username_or_email = request.POST.get("username_or_email")
        password = request.POST.get("password")

        # Try to get user by username or email
        try:
            user_obj = User.objects.get(Q(username=username_or_email) | Q(email=username_or_email))
        except User.DoesNotExist:
            messages.warning(request, "Invalid credentials.")
            return redirect("userauths:login")  # Redirect back to the login page

        # Check password
        if user_obj.check_password(password):
            if user_obj.is_active:
                login(request, user_obj)
                messages.success(request, "You are logged in")
                return redirect("core:index")
            else:
                messages.warning(request, "Your account is not activated. Please check your email for the activation code.")
                return redirect("userauths:login")  # Redirect back to the login page
        else:
            messages.warning(request, "Invalid credentials.")
            return redirect("userauths:login")  # Redirect back to the login page

    context = {}
    return render(request, "userauths/login.html", context)





@login_required
def logout_view(request):
    logout(request)
    messages.success(request, "You logged out.")
    return redirect('userauths:login')


from django.urls import reverse_lazy


class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'userauths/change-password.html'
    form_class = CustomPasswordChangeForm
    success_url = reverse_lazy('core:index')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Your password was changed successfully')
        return response

    def form_invalid(self, form):
        error_messages = form.errors
        for field, errors in error_messages.items():
            for error in errors:
                if field == '__all__':  # Global form errors
                    messages.warning(self.request, error)
                else:
                    messages.warning(self.request, f"{error}")

        return super().form_invalid(form)

    


def activate_account_view(request):
    if request.method == 'POST':
        activation_code = request.POST.get('code')

        # Check if the activation code exists in the database
        try:
            user = User.objects.get(activation_code=activation_code)
        except User.DoesNotExist:
            messages.warning(request, 'Invalid activation code. Please try again.')
            return redirect('userauths:activate')  # Redirect back to the activation page for another attempt

        # Activate the user's account
        user.is_active = True
        user.activation_code = None  # Clear activation code after activation
        user.save()

        # Log in the user
        login(request, user)

        messages.success(request, 'Your account has been activated successfully!')
        return redirect('core:index')  # Redirect to the index page after activation

    return render(request, 'userauths/activate.html')






User = get_user_model()








def activate_account(request):
    if request.method == "POST":
        email = request.POST.get("email_activate")

        try:
            user = User.objects.get(email=email)
            if user.is_active:
                messages.warning(request, "Your account is already activated.")
            else:
                # Generate activation code
                user.activation_code = generate_activation_code()  # Generate activation code
                user.save()
                
                # Send activation email
                subject = 'Activate Your Account'
                message = f"""Hi {user.username},

Thank you for registering with us! To complete the registration process and start using your account, please use the following activation code:
Activation Code: {user.activation_code}

Enter this activation code on the activation page to activate your account.

If you didn't register for an account with us, please disregard this email.

Best regards,
Vishw Electronics"""
                from_email = 'khatik.rk111@gmail.com'  # Replace with your email
                to_email = user.email
                send_mail(subject, message, from_email, [to_email])
                
                # Save the activation code to the user object
                
                
                messages.success(request, "Activation code sent successfully. Please check your email.")
                return redirect("userauths:activate-code")
        except User.DoesNotExist:
            messages.warning(request, "No user found with this email address.")

    return render(request, "userauths/activate_account.html")

def activate_code(request):
  if request.method == 'POST':
        activation_code = request.POST.get('activation_code')

        # Check if the activation code exists in the database
        try:
            user = User.objects.get(activation_code=activation_code)
        except User.DoesNotExist:
            messages.warning(request, 'Invalid activation code. Please try again.')
            return redirect('userauths:activate-code')  # Redirect back to the activation page for another attempt

        # Activate the user's account
        user.is_active = True
        user.activation_code = None  # Clear activation code after activation
        user.save()
        
        messages.success(request, "Your account is activated successfully, now you can login")
        return redirect('userauths:login')

  return render(request, "userauths/activate_code.html")

templates/userauths/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!--=====================================
                    META TAG PART START
        =======================================-->
        <!-- REQUIRE META -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- AUTHOR META -->
        <meta name="author" content="mironcoder">
        <meta name="email" content="mironcoder@gmail.com">
        <meta name="profile" content="https://themeforest.net/user/mironcoder">

        <!-- TEMPLATE META -->
        <meta name="name" content="Greeny">
        <meta name="title" content="Greeny - eCommerce HTML Template">
        <meta name="keywords" content="organic, food, shop, ecommerce, store, html, bootstrap, template, agriculture, vegetables, webshop, farm, grocery, natural, online store">
        <!--=====================================
                    META-TAG PART END
        =======================================-->

        <!-- WEBPAGE TITLE -->
        <title>Vishw - Login</title>

        <!--=====================================
                    CSS LINK PART START
        =======================================-->
        <!-- FAVICON -->
        <link rel="icon" href="{% static 'images/logo.png' %}">

        <!-- FONTS -->
        <link rel="stylesheet" href="{% static 'fonts/flaticon/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/icofont/icofont.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/fontawesome/fontawesome.min.css' %}">

        <!-- VENDOR -->
        <link rel="stylesheet" href="{% static 'vendor/venobox/venobox.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/slickslider/slick.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/niceselect/nice-select.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">

        <!-- CUSTOM -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/user-auth.css' %}">
        <!--=====================================
                    CSS LINK PART END
        =======================================-->
    </head>
    <body>
        <!--=====================================
                    USER FORM PART START
        =======================================-->
        <section class="user-form-part">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-sm-10 col-md-12 col-lg-12 col-xl-10">
                        <div class="user-form-logo">
                            <a href={% url 'core:index' %}><img src="{% static 'images/logo.png' %}" alt="logo"></a>
                        </div>
                        
                        <div class="container-alert">
                        {% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'warning' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
            <strong>{{ message }}</strong>
        </div>
        <script>
            // Function to remove the alert after a certain time
            setTimeout(function() {
                $('.alert').fadeOut('slow', function() {
                    $(this).remove();
                });
            }, 5000); // 5000 milliseconds = 5 seconds. Change this value to adjust the duration.
        </script>
    {% endfor %}
{% endif %}
    </div>

                    
                        <div class="user-form-card">
                            <div class="user-form-title">
                                <h2>welcome!</h2>
                                <p>Use your credentials to access</p>
                            </div>
                            <div class="user-form-group">
                                <!--<ul class="user-form-social">
                                    <li><a href="#" class="facebook"><i class="fab fa-facebook-f"></i>login with facebook</a></li>
                                    <li><a href="#" class="twitter"><i class="fab fa-twitter"></i>login with twitter</a></li>
                                    <li><a href="#" class="google"><i class="fab fa-google"></i>login with google</a></li>
                                    <li><a href="#" class="instagram"><i class="fab fa-instagram"></i>login with instagram</a></li>
                                </ul>
                                <div class="user-form-divider">
                                    <p>or</p>
                                </div>-->
                                <form method = "POST" action = "" class="user-form">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="text" name = "username_or_email" class="form-control" placeholder="Enter your username or email">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name = "password" class="form-control" placeholder="Enter your password">
                                    </div>
                                    <!--<div class="form-check mb-3">
                                        <input class="form-check-input" type="checkbox" value="" id="check">
                                        <label class="form-check-label" for="check">Remember Me</label>
                                    </div>-->
                                    <div class="form-button">
                                        <button type="submit">login</button>
                                        <p>Forgot your password?<a href="{% url "reset_password" %}">reset here</a></p>
                                        <p>Haven't activated your account yet?<a href="{% url "userauths:activate-account" %}">Activate it now!</a></p>
                                        <p>
                                    </div>
                                </form>
                                
                            </div>
                        </div>
                        <div class="user-form-remind">
                            <p>Don't have any account?<a href={% url 'userauths:sign-up' %}>register here</a></p>
                        </div>
                        <div class="user-form-footer">
                            <p>Vishw | &COPY; Copyright by <a href="#">Vishw Electronics</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
      
        
        
        <!--=====================================
                    USER FORM PART END
        =======================================-->


        <!--=====================================
                    JS LINK PART START
        =======================================-->
        <!-- VENDOR -->
        <script src="{% static 'vendor/bootstrap/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendor/countdown/countdown.min.js' %}"></script>
        <script src="{% static 'vendor/niceselect/nice-select.min.js' %}"></script>
        <script src="{% static 'vendor/slickslider/slick.min.js' %}"></script>
        <script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>

        <!-- CUSTOM -->
        <script src="{% static 'js/nice-select.js' %}"></script>
        <script src="{% static 'js/countdown.js' %}"></script>
        <script src="{% static 'js/accordion.js' %}"></script>
        <script src="{% static 'js/venobox.js' %}"></script>
        <script src="{% static 'js/slick.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script> 
        <!--=====================================
                    JS LINK PART END
        =======================================-->
    </body>
</html>

templates/userauths/sign-up.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- META TAG PART START -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="mironcoder">
    <meta name="email" content="mironcoder@gmail.com">
    <meta name="profile" content="https://themeforest.net/user/mironcoder">
    <meta name="name" content="Greeny">
    <meta name="title" content="Greeny - eCommerce HTML Template">
    <meta name="keywords" content="organic, food, shop, ecommerce, store, html, bootstrap, template, agriculture, vegetables, webshop, farm, grocery, natural, online store">
    <!-- META-TAG PART END -->

    <!-- WEBPAGE TITLE -->
    <title>Vishw - Register</title>

    <!-- CSS LINK PART START -->
    <!-- FAVICON -->
    <link rel="icon" href="{% static 'images/logo.png' %}">

    <!-- FONTS -->
    <link rel="stylesheet" href="{% static 'fonts/flaticon/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icofont/icofont.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/fontawesome.min.css' %}">

    <!-- VENDOR -->
    <link rel="stylesheet" href="{% static 'vendor/venobox/venobox.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/slickslider/slick.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/niceselect/nice-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">

    <!-- CUSTOM -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/user-auth.css' %}">
    <!-- CSS LINK PART END -->
</head>
<body>

<!-- USER FORM PART START -->
<section class="user-form-part">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-10 col-md-12 col-lg-12 col-xl-10">
                <div class="user-form-logo">
                    <a href="{% url 'core:index' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
                </div>
                <div class="container-alert">
                    {% if messages %}
{% for message in messages %}
    <div class="alert {% if message.tags == 'warning' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
        <strong>{{ message }}</strong>
    </div>
    <script>
        // Function to remove the alert after a certain time
        setTimeout(function() {
            $('.alert').fadeOut('slow', function() {
                $(this).remove();
            });
        }, 5000); // 5000 milliseconds = 5 seconds. Change this value to adjust the duration.
    </script>
{% endfor %}
{% endif %}
</div>
                <div class="user-form-card">
                    <div class="user-form-title">
                        <h2>Join Now!</h2>
                        <p>Setup A New Account In A Minute</p>
                    </div>
                    <div class="user-form-group">
                       <!-- <ul class="user-form-social">
                            <li><a href="#" class="facebook"><i class="fab fa-facebook-f"></i>Join with facebook</a></li>
                            <li><a href="#" class="twitter"><i class="fab fa-twitter"></i>Join with twitter</a></li>
                            <li><a href="#" class="google"><i class="fab fa-google"></i>Join with google</a></li>
                            <li><a href="#" class="instagram"><i class="fab fa-instagram"></i>Join with instagram</a></li>
                        </ul>
                        <div class="user-form-divider">
                            <p>or</p>
                        </div>-->
                        <form method="post" action="" class="user-form">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                {{ form.email }}
                            </div>
                            <div class="form-group">
                                {{ form.password1 }}
                            </div>
                            <div class="form-group">
                                {{ form.password2 }}
                            </div>
                            <div class="form-button">
                                <button type="submit">register</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="user-form-remind">
                    <p>Already Have An Account?<a href="{% url 'userauths:login' %}">login here</a></p>
                </div>
                <div class="user-form-footer">
                    <p>Vishw | &COPY; Copyright by <a href="#">Vishw Electronics</a></p>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- USER FORM PART END -->

<!-- JS LINK PART START -->
<!-- VENDOR -->
<script src="{% static 'vendor/bootstrap/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/countdown/countdown.min.js' %}"></script>
<script src="{% static 'vendor/niceselect/nice-select.min.js' %}"></script>
<script src="{% static 'vendor/slickslider/slick.min.js' %}"></script>
<script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>

<!-- CUSTOM -->
<script src="{% static 'js/nice-select.js' %}"></script>
<script src="{% static 'js/countdown.js' %}"></script>
<script src="{% static 'js/accordion.js' %}"></script>
<script src="{% static 'js/venobox.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- JS LINK PART END -->

</body>
</html>