core/urls.py
from django.urls import path, include
#from core.views import index
from core import views

app_name = 'core'

urlpatterns = [
    #index page
    path('', views.index, name = "index"),

    #shop page
    path('products/', views.product_list, name = 'product'),

    #product-detail page
    path('product/<pid>/', views.product_detail_view, name = 'product-detail'),

    #category
    path('category/', views.category_list_view, name = 'category'),

    #category product list 
    path('category/<cid>/', views.category_product_list_view, name = 'category-product-list'),

    #tag product list
    path('products/tag/<slug:tag_slug>/', views.tag_list, name="tags"),
    
    #review
    path('ajax-add-review/<int:pid>/', views.ajax_add_review, name='ajax_add_review'),

    #search
    path('search/', views.search_view, name='search'),

    #filter-product
    #path('filter-product/', views.filter_product, name="filter-product"),

    #cart
    path('add-to-cart/', views.add_to_cart, name = 'add-to-cart'),
    path('cart/', views.cart_view, name='cart'),
    path('delete-from-cart/', views.delete_item_from_cart, name='delete-from-cart'),
    path('update-cart', views.update_cart, name='update-cart'),

    #checkout
    path('checkout/', views.checkout_view, name='checkout'),

    #paypal payment
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-completed/', views.payment_completed_view, name='payment-completed'),
    path('payment-failed/', views.payment_failed_view, name='payment-failed'),
    
    #user profile
    path('dashboard/', views.customer_dashboard, name='dashboard'),
    path('delete_contact/', views.delete_contact, name='delete-contact'),
    path('delete_address/', views.delete_address, name='delete-address'),

    #Brand
    path('brand/<bid>/', views.brand_product_list_view, name = 'brand-product-list'),

    #wishlist
    path('wishlist/', views.wishlist_view, name = 'wishlist'),
    path('add-to-wishlist/', views.add_to_wishlist, name='add-to-wishlist'),
    path('remove-from-wishlist/', views.remove_wishlist, name='remove-from-wishlist'),

    #contact us
    path('contact/', views.Contact_us_view, name='contact'),

    #order
    path('orders/', views.orders_view, name='Orders'),

    #invoice pdf download
    path('invoice/', views.Invoice, name='Invoice'),
    
    #get total cart amount every second
    #path('get_cart_total/', views.get_cart_total, name='get_cart_total')

    #determine the address selectd by the user on the invoice page
    path('update_selected_address/', views.update_selected_address, name='selected_address'),

    #stripe payment
    #path('create_checkout_session/', views.create_checkout_session, name='create-checkout-session'), 

    #privacy policy page
    path('privacy-policy/', views.privacy, name='privacy-policy'),


    #order invoice from order page
    path('order_invoice/<int:order_id>/' , views.order_invoice, name='Order_invoice'),

    #Terms-conditions page
    path('terms-conditions/', views.Terms_Conditions, name='terms-conditions'),

 
    



   
    






]

userauths/urls.py
from django.urls import path
from userauths import views
from userauths.views import CustomPasswordChangeView


app_name = 'userauths'

urlpatterns = [
    path("sign-up/", views.register_view, name = "sign-up"),
    path("login/", views.login_view, name = "login"),
    path("sign-out/", views.logout_view, name = "sign-out"),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change-password'),
    path('activate/', views.activate_account_view, name="activate"),
   path('activate_account/', views.activate_account, name="activate-account"),
   path('activation-code', views.activate_code, name="activate-code")

]

vishw/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path('User/', include("userauths.urls")), 

    path('ckeditor/', include("ckeditor_uploader.urls")), 

    path('reset_password', auth_views.PasswordResetView.as_view(template_name="reset_password.html"), name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_send.html"), name="password_reset_done"),

    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html"), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name="password_reset_complete"),
]

if settings.DEBUG:
     urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/password_reset_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!--=====================================
                    META TAG PART START
        =======================================-->
        <!-- REQUIRE META -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- AUTHOR META -->
        <meta name="author" content="mironcoder">
        <meta name="email" content="mironcoder@gmail.com">
        <meta name="profile" content="https://themeforest.net/user/mironcoder">

        <!-- TEMPLATE META -->
        <meta name="name" content="Greeny">
        <meta name="title" content="Greeny - eCommerce HTML Template">
        <meta name="keywords" content="organic, food, shop, ecommerce, store, html, bootstrap, template, agriculture, vegetables, webshop, farm, grocery, natural, online store">
        <!--=====================================
                    META-TAG PART END
        =======================================-->

        <!-- WEBPAGE TITLE -->
        <title>Vishw - Login</title>

        <!--=====================================
                    CSS LINK PART START
        =======================================-->
        <!-- FAVICON -->
        <link rel="icon" href="{% static 'images/logo.png' %}">

        <!-- FONTS -->
        <link rel="stylesheet" href="{% static 'fonts/flaticon/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/icofont/icofont.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/fontawesome/fontawesome.min.css' %}">

        <!-- VENDOR -->
        <link rel="stylesheet" href="{% static 'vendor/venobox/venobox.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/slickslider/slick.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/niceselect/nice-select.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">

        <!-- CUSTOM -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/user-auth.css' %}">
        <!--=====================================
                    CSS LINK PART END
        =======================================-->
    </head>
    <body>
        <!--=====================================
                    USER FORM PART START
        =======================================-->
        <section class="user-form-part">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-sm-10 col-md-12 col-lg-12 col-xl-10">
                        <div class="user-form-logo">
                            <a href={% url 'core:index' %}><img src="{% static 'images/logo.png' %}" alt="logo"></a>
                        </div>
                        {% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'warning' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
            <strong>{{ message }}</strong>
        </div>
        <script>
            // Function to remove the alert after a certain time
            setTimeout(function() {
                $('.alert').fadeOut('slow', function() {
                    $(this).remove();
                });
            }, 5000); // 5000 milliseconds = 5 seconds. Change this value to adjust the duration.
        </script>
    {% endfor %}
{% endif %}

                    
                        <div class="user-form-card">
                            <div class="user-form-title">
                               
                                <p>Your password has been set. You may go ahead and log in now.</p>
                            </div>
                            <div class="user-form-group">
                                <form method = "POST" action = "" class="user-form">
                                    {% csrf_token %}
                                    <div class="form-button">
                                        <a href="{% url 'userauths:login' %}" class="btn btn-primary">Login</a>

                                       
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    USER FORM PART END
        =======================================-->


        <!--=====================================
                    JS LINK PART START
        =======================================-->
        <!-- VENDOR -->
        <script src="{% static 'vendor/bootstrap/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendor/countdown/countdown.min.js' %}"></script>
        <script src="{% static 'vendor/niceselect/nice-select.min.js' %}"></script>
        <script src="{% static 'vendor/slickslider/slick.min.js' %}"></script>
        <script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>

        <!-- CUSTOM -->
        <script src="{% static 'js/nice-select.js' %}"></script>
        <script src="{% static 'js/countdown.js' %}"></script>
        <script src="{% static 'js/accordion.js' %}"></script>
        <script src="{% static 'js/venobox.js' %}"></script>
        <script src="{% static 'js/slick.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script> 
        <!--=====================================
                    JS LINK PART END
        =======================================-->
    </body>
</html>

templates/password_reset_confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!--=====================================
                    META TAG PART START
        =======================================-->
        <!-- REQUIRE META -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- AUTHOR META -->
        <meta name="author" content="mironcoder">
        <meta name="email" content="mironcoder@gmail.com">
        <meta name="profile" content="https://themeforest.net/user/mironcoder">

        <!-- TEMPLATE META -->
        <meta name="name" content="Greeny">
        <meta name="title" content="Greeny - eCommerce HTML Template">
        <meta name="keywords" content="organic, food, shop, ecommerce, store, html, bootstrap, template, agriculture, vegetables, webshop, farm, grocery, natural, online store">
        <!--=====================================
                    META-TAG PART END
        =======================================-->

        <!-- WEBPAGE TITLE -->
        <title>Vishw - Login</title>

        <!--=====================================
                    CSS LINK PART START
        =======================================-->
        <!-- FAVICON -->
        <link rel="icon" href="{% static 'images/logo.png' %}">

        <!-- FONTS -->
        <link rel="stylesheet" href="{% static 'fonts/flaticon/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/icofont/icofont.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/fontawesome/fontawesome.min.css' %}">

        <!-- VENDOR -->
        <link rel="stylesheet" href="{% static 'vendor/venobox/venobox.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/slickslider/slick.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/niceselect/nice-select.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">

        <!-- CUSTOM -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/user-auth.css' %}">
        <!--=====================================
                    CSS LINK PART END
        =======================================-->
    </head>
    <body>
        <!--=====================================
                    USER FORM PART START
        =======================================-->
        <section class="user-form-part">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-sm-10 col-md-12 col-lg-12 col-xl-10">
                        <div class="user-form-logo">
                            <a href={% url 'core:index' %}><img src="{% static 'images/logo.png' %}" alt="logo"></a>
                        </div>
                        {% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'warning' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
            <strong>{{ message }}</strong>
        </div>
        <script>
            // Function to remove the alert after a certain time
            setTimeout(function() {
                $('.alert').fadeOut('slow', function() {
                    $(this).remove();
                });
            }, 5000); // 5000 milliseconds = 5 seconds. Change this value to adjust the duration.
        </script>
    {% endfor %}
{% endif %}

                    
                        <div class="user-form-card">
                            <div class="user-form-title">
                                <h2>Worried!</h2>
                                <p>Just follow the simple steps here</p>
                            </div>
                            <div class="user-form-group">
                                <form method="post" action="" class="user-form">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="password" name="new_password1" class="form-control" placeholder="New password">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="new_password2" class="form-control" placeholder="Confirm new password">
                                    </div>
                                    <div class="form-button">
                                        <button type="submit">Reset Password</button>
                                    </div>
                                </form>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    USER FORM PART END
        =======================================-->


        <!--=====================================
                    JS LINK PART START
        =======================================-->
        <!-- VENDOR -->
        <script src="{% static 'vendor/bootstrap/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendor/countdown/countdown.min.js' %}"></script>
        <script src="{% static 'vendor/niceselect/nice-select.min.js' %}"></script>
        <script src="{% static 'vendor/slickslider/slick.min.js' %}"></script>
        <script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>

        <!-- CUSTOM -->
        <script src="{% static 'js/nice-select.js' %}"></script>
        <script src="{% static 'js/countdown.js' %}"></script>
        <script src="{% static 'js/accordion.js' %}"></script>
        <script src="{% static 'js/venobox.js' %}"></script>
        <script src="{% static 'js/slick.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script> 
        <!--=====================================
                    JS LINK PART END
        =======================================-->
    </body>
</html>

templates/reset_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!--=====================================
                    META TAG PART START
        =======================================-->
        <!-- REQUIRE META -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- AUTHOR META -->
        <meta name="author" content="mironcoder">
        <meta name="email" content="mironcoder@gmail.com">
        <meta name="profile" content="https://themeforest.net/user/mironcoder">

        <!-- TEMPLATE META -->
        <meta name="name" content="Greeny">
        <meta name="title" content="Greeny - eCommerce HTML Template">
        <meta name="keywords" content="organic, food, shop, ecommerce, store, html, bootstrap, template, agriculture, vegetables, webshop, farm, grocery, natural, online store">
        <!--=====================================
                    META-TAG PART END
        =======================================-->

        <!-- WEBPAGE TITLE -->
        <title>Vishw - Reset Password</title>

        <!--=====================================
                    CSS LINK PART START
        =======================================-->
        <!-- FAVICON -->
        <link rel="icon" href="{% static 'images/logo.png' %}">

        <!-- FONTS -->
        <link rel="stylesheet" href="{% static 'fonts/flaticon/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/icofont/icofont.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/fontawesome/fontawesome.min.css' %}">

        <!-- VENDOR -->
        <link rel="stylesheet" href="{% static 'vendor/venobox/venobox.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/slickslider/slick.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/niceselect/nice-select.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">

        <!-- CUSTOM -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/user-auth.css' %}">
        <!--=====================================
                    CSS LINK PART END
        =======================================-->
    </head>
    <body>
        <!--=====================================
                    USER FORM PART START
        =======================================-->
        <section class="user-form-part">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-sm-10 col-md-12 col-lg-12 col-xl-10">
                        <div class="user-form-logo">
                            <a href={% url 'core:index' %}><img src="{% static 'images/logo.png' %}" alt="logo"></a>
                        </div>
                        {% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'warning' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
            <strong>{{ message }}</strong>
        </div>
        <script>
            // Function to remove the alert after a certain time
            setTimeout(function() {
                $('.alert').fadeOut('slow', function() {
                    $(this).remove();
                });
            }, 5000); // 5000 milliseconds = 5 seconds. Change this value to adjust the duration.
        </script>
    {% endfor %}
{% endif %}

                    
                        <div class="user-form-card">
                            <div class="user-form-title">
                                <h2>Worried!</h2>
                                <p>Just follow the simple steps here</p>
                            </div>
                            <div class="user-form-group">
                                <form method = "POST" action = "" class="user-form">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="email" name="{{ form.email.name }}" class="form-control" value="{{ form.email.value|default_if_none:'' }}" placeholder="Enter your email">
                                    </div>
                                    <div class="form-button">
                                        <button type="submit">sent email</button>
                                       
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    USER FORM PART END
        =======================================-->


        <!--=====================================
                    JS LINK PART START
        =======================================-->
        <!-- VENDOR -->
        <script src="{% static 'vendor/bootstrap/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendor/countdown/countdown.min.js' %}"></script>
        <script src="{% static 'vendor/niceselect/nice-select.min.js' %}"></script>
        <script src="{% static 'vendor/slickslider/slick.min.js' %}"></script>
        <script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>

        <!-- CUSTOM -->
        <script src="{% static 'js/nice-select.js' %}"></script>
        <script src="{% static 'js/countdown.js' %}"></script>
        <script src="{% static 'js/accordion.js' %}"></script>
        <script src="{% static 'js/venobox.js' %}"></script>
        <script src="{% static 'js/slick.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script> 
        <!--=====================================
                    JS LINK PART END
        =======================================-->
    </body>
</html>

templates/reset_password_send.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!--=====================================
                    META TAG PART START
        =======================================-->
        <!-- REQUIRE META -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- AUTHOR META -->
        <meta name="author" content="mironcoder">
        <meta name="email" content="mironcoder@gmail.com">
        <meta name="profile" content="https://themeforest.net/user/mironcoder">

        <!-- TEMPLATE META -->
        <meta name="name" content="Greeny">
        <meta name="title" content="Greeny - eCommerce HTML Template">
        <meta name="keywords" content="organic, food, shop, ecommerce, store, html, bootstrap, template, agriculture, vegetables, webshop, farm, grocery, natural, online store">
        <!--=====================================
                    META-TAG PART END
        =======================================-->

        <!-- WEBPAGE TITLE -->
        <title>Vishw - Login</title>

        <!--=====================================
                    CSS LINK PART START
        =======================================-->
        <!-- FAVICON -->
        <link rel="icon" href="{% static 'images/logo.png' %}">

        <!-- FONTS -->
        <link rel="stylesheet" href="{% static 'fonts/flaticon/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/icofont/icofont.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/fontawesome/fontawesome.min.css' %}">

        <!-- VENDOR -->
        <link rel="stylesheet" href="{% static 'vendor/venobox/venobox.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/slickslider/slick.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/niceselect/nice-select.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">

        <!-- CUSTOM -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/user-auth.css' %}">
        <!--=====================================
                    CSS LINK PART END
        =======================================-->
    </head>
    <body>
        <!--=====================================
                    USER FORM PART START
        =======================================-->
        <section class="user-form-part">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-sm-10 col-md-12 col-lg-12 col-xl-10">
                        <div class="user-form-logo">
                            <a href={% url 'core:index' %}><img src="{% static 'images/logo.png' %}" alt="logo"></a>
                        </div>
                        {% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'warning' %}alert-danger{% else %}alert-success{% endif %}" role="alert">
            <strong>{{ message }}</strong>
        </div>
        <script>
            // Function to remove the alert after a certain time
            setTimeout(function() {
                $('.alert').fadeOut('slow', function() {
                    $(this).remove();
                });
            }, 5000); // 5000 milliseconds = 5 seconds. Change this value to adjust the duration.
        </script>
    {% endfor %}
{% endif %}

                    
                        <div class="user-form-card">
                            <div class="user-form-title">
                             
                               <p> We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

                                If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
                            </div>
                         
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    USER FORM PART END
        =======================================-->


        <!--=====================================
                    JS LINK PART START
        =======================================-->
        <!-- VENDOR -->
        <script src="{% static 'vendor/bootstrap/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendor/countdown/countdown.min.js' %}"></script>
        <script src="{% static 'vendor/niceselect/nice-select.min.js' %}"></script>
        <script src="{% static 'vendor/slickslider/slick.min.js' %}"></script>
        <script src="{% static 'vendor/venobox/venobox.min.js' %}"></script>

        <!-- CUSTOM -->
        <script src="{% static 'js/nice-select.js' %}"></script>
        <script src="{% static 'js/countdown.js' %}"></script>
        <script src="{% static 'js/accordion.js' %}"></script>
        <script src="{% static 'js/venobox.js' %}"></script>
        <script src="{% static 'js/slick.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script> 
        <!--=====================================
                    JS LINK PART END
        =======================================-->
    </body>
</html>